/**
 * Admin PJAX Router — Intercepts navigation links, fetches HTML partials,
 * swaps #page-content, and manages browser history.
 *
 * Depends on: jQuery (core.js), feather-icons, bootstrap
 */

const AdminRouter = {
    /** @type {Object<string, Function>} Page init registry: pattern → initFn */
    _pageRegistry: {},

    /** @type {AbortController|null} Current in-flight fetch */
    _abortController: null,

    /** @type {boolean} Whether router is initialized */
    _initialized: false,

    /**
     * Initialize the PJAX router
     */
    init() {
        if (this._initialized) return;
        this._initialized = true;

        // Some mobile browsers use the first tap on this legacy sidebar only
        // to focus its link. Handle the completed touch directly so navigation
        // happens on that first tap, before the synthetic click is emitted.
        document.addEventListener('touchend', (e) => {
            if (!window.matchMedia('(max-width: 991px)').matches) return;

            const link = e.target.closest('.sidebar a.nav-link[data-pjax]');
            if (!link) return;

            this._handlePjaxLink(e, link);
        }, { capture: true, passive: false });

        // Capture the click before the legacy sidebar handler runs. This also
        // covers desktop navigation and mobile browsers without touch events.
        document.addEventListener('click', (e) => {
            const link = e.target.closest('a[data-pjax]');
            if (!link) return;

            this._handlePjaxLink(e, link);
        }, true);

        // Handle browser back/forward
        window.addEventListener('popstate', () => {
            this._load(window.location.pathname + window.location.search, false);
        });

        this._updateSidebarActive(window.location.pathname + window.location.search);
    },

    /**
     * Navigate from a PJAX link, regardless of whether it was tapped or clicked.
     * @param {Event} e
     * @param {HTMLAnchorElement} link
     */
    _handlePjaxLink(e, link) {

            // Skip conditions
            if (link.getAttribute('data-pjax') === 'false') return;
            if (link.getAttribute('target') === '_blank') return;
            if (e.ctrlKey || e.metaKey || e.shiftKey) return;

            let href = link.getAttribute('href');
            if (!href || href === '#' || href.startsWith('javascript:')) return;

            // Extract pathname from absolute URLs (e.g. generated by Laravel's route() helper)
            if (href.startsWith('http')) {
                try {
                    const parsedUrl = new URL(href);
                    href = parsedUrl.pathname + parsedUrl.search;
                } catch (e) {
                    return;
                }
            }

            e.preventDefault();

            // Don't navigate to the same URL
            if (this._normalizeUrl(href) === this._normalizeUrl(window.location.pathname + window.location.search)) return;

            this._closeMobileSidebar(link);
            this.navigate(href);
    },

    /**
     * Navigate to a URL via PJAX
     * @param {string} url
     */
    navigate(url) {
        // Push state first, then load
        history.pushState(null, '', url);
        this._load(url, true);
    },

    /**
     * Register a page initializer
     * @param {string|RegExp} pattern - URL pattern to match
     * @param {Function} initFn - Function to call after page content is loaded
     */
    registerPage(pattern, initFn) {
        this._pageRegistry[pattern] = initFn;
    },

    /**
     * Internal: Load URL content via PJAX
     * @param {string} url
     * @param {boolean} isPush - Whether this is a push (not popstate)
     */
    async _load(url, isPush) {
        // Abort any in-flight request
        if (this._abortController) {
            this._abortController.abort();
        }
        this._abortController = new AbortController();

        const pageContent = document.getElementById('page-content');
        if (!pageContent) {
            window.location.href = url;
            return;
        }

        // Show progress bar
        this._showProgress();
        pageContent.classList.add('pjax-loading');

        try {
            const response = await fetch(url, {
                headers: {
                    'X-PJAX': '1',
                    'X-Requested-With': 'XMLHttpRequest',
                    'Accept': 'text/html',
                },
                signal: this._abortController.signal,
            });

            if (!response.ok) {
                // On error, fall back to full page load
                window.location.href = url;
                return;
            }

            // Check for redirect (e.g., auth redirect)
            if (response.redirected) {
                window.location.href = response.url;
                return;
            }

            const html = await response.text();

            // Swap content
            pageContent.innerHTML = html;
            pageContent.classList.remove('pjax-loading');

            // Post-swap tasks
            this._afterSwap(url);
            this._hideProgress();

        } catch (err) {
            if (err.name === 'AbortError') return; // Aborted by newer request
            console.error('[AdminRouter] PJAX load failed:', err);
            window.location.href = url; // Fallback to full page load
        }
    },

    /**
     * Run post-swap tasks after content is replaced
     * @param {string} url
     */
    _afterSwap(url) {
        // Re-initialize feather icons with validation
        setTimeout(() => {
            if (typeof feather !== 'undefined' && feather.icons) {
                const pageContent = document.getElementById('page-content');
                if (pageContent) {
                    const icons = pageContent.querySelectorAll('i[data-feather]');
                    icons.forEach(icon => {
                        const iconName = icon.getAttribute('data-feather');
                        if (iconName && feather.icons[iconName]) {
                            const svg = feather.icons[iconName].toSvg({
                                class: icon.className,
                                'stroke-width': icon.getAttribute('stroke-width') || 2
                            });
                            icon.outerHTML = svg;
                        }
                    });
                }
            }
        }, 100);

        // Re-initialize Bootstrap tooltips
        const tooltipTriggerList = document.querySelectorAll('#page-content [data-bs-toggle="tooltip"]');
        tooltipTriggerList.forEach((el) => new bootstrap.Tooltip(el));

        // Re-initialize Bootstrap popovers
        const popoverTriggerList = document.querySelectorAll('#page-content [data-bs-toggle="popover"]');
        popoverTriggerList.forEach((el) => new bootstrap.Popover(el));

        // Update active sidebar item
        this._updateSidebarActive(url);

        // Update page title if provided
        const titleEl = document.querySelector('#page-content [data-page-title]');
        if (titleEl) {
            document.title = titleEl.getAttribute('data-page-title') + ' — Admin';
        }

        // Scroll to top of content
        window.scrollTo({ top: 0, behavior: 'auto' });

        // Run registered page initializer
        this._runPageInit(url);
    },

    /**
     * Update sidebar active state based on current URL
     * @param {string} url
     */
    _updateSidebarActive(url) {
        const sidebar = document.querySelector('.sidebar');
        if (!sidebar) return;

        // Remove all active classes
        sidebar.querySelectorAll('.nav-item.active, .nav-item.pjax-active').forEach((el) => {
            el.classList.remove('active', 'pjax-active');
        });
        sidebar.querySelectorAll('.nav-link.active').forEach((el) => {
            el.classList.remove('active');
            el.removeAttribute('aria-current');
        });
        sidebar.querySelectorAll('.collapse.show').forEach((el) => {
            el.classList.remove('show');
        });

        // Find matching link and activate
        const path = this._normalizePath(url);
        const links = sidebar.querySelectorAll('.nav-link[data-pjax]');

        let bestMatch = null;
        let bestLength = 0;

        links.forEach((link) => {
            const href = this._normalizePath(link.getAttribute('href'));
            if (!href) return;

            const isExactMatch = path === href;
            const isNestedMatch = href !== '/'
                && path.startsWith(`${href}/`);

            if ((isExactMatch || isNestedMatch) && href.length > bestLength) {
                bestMatch = link;
                bestLength = href.length;
            }
        });

        if (bestMatch) {
            bestMatch.classList.add('active');
            bestMatch.setAttribute('aria-current', 'page');

            const navItem = bestMatch.closest('.nav-item');
            if (navItem) {
                navItem.classList.add('active', 'pjax-active');
            }

            // Open parent collapse if inside a submenu
            const collapse = bestMatch.closest('.collapse');
            if (collapse) {
                collapse.classList.add('show');
                const parentItem = collapse.closest('.nav-item');
                if (parentItem) parentItem.classList.add('active');
            }
        }
    },

    _normalizePath(url) {
        if (!url) return '';

        try {
            const parsedUrl = new URL(url, window.location.origin);
            const normalizedPath = parsedUrl.pathname.replace(/\/$/, '');

            return normalizedPath === '' ? '/' : normalizedPath;
        } catch (err) {
            const fallbackPath = String(url).split('?')[0].split('#')[0].replace(/\/$/, '');

            return fallbackPath === '' ? '/' : fallbackPath;
        }
    },

    _normalizeUrl(url) {
        if (!url) return '';

        try {
            const parsedUrl = new URL(url, window.location.origin);
            const normalizedPath = parsedUrl.pathname.replace(/\/$/, '') || '/';

            return normalizedPath + parsedUrl.search;
        } catch (err) {
            const [pathPart, searchPart = ''] = String(url).split('?');
            const normalizedPath = pathPart.replace(/\/$/, '') || '/';

            return normalizedPath + (searchPart !== '' ? `?${searchPart}` : '');
        }
    },

    /**
     * Close the mobile sidebar after choosing a sidebar destination.
     * @param {HTMLAnchorElement} link
     */
    _closeMobileSidebar(link) {
        if (!window.matchMedia('(max-width: 991px)').matches || !link.closest('.sidebar')) {
            return;
        }

        document.body.classList.remove('sidebar-open');
        document.querySelectorAll('.sidebar-header .sidebar-toggler').forEach((toggler) => {
            toggler.classList.remove('active');
            toggler.classList.add('not-active');
        });
    },

    /**
     * Run the registered page initializer matching the URL
     * @param {string} url
     */
    _runPageInit(url) {
        const path = url.split('?')[0];

        for (const [pattern, initFn] of Object.entries(this._pageRegistry)) {
            let matched = false;

            if (pattern instanceof RegExp) {
                matched = pattern.test(path);
            } else if (typeof pattern === 'string') {
                // Support simple wildcard matching: /admin/products/* matches /admin/products/create
                if (pattern.endsWith('/*')) {
                    matched = path.startsWith(pattern.slice(0, -2));
                } else {
                    matched = path === pattern;
                }
            }

            if (matched) {
                try {
                    initFn(path);
                } catch (err) {
                    console.error(`[AdminRouter] Page init error for ${pattern}:`, err);
                }
            }
        }
    },

    /**
     * Show the progress bar
     */
    _showProgress() {
        let bar = document.getElementById('pjax-progress');
        if (!bar) return;

        // Reset
        bar.classList.remove('done');
        bar.style.width = '0';

        // Force reflow
        void bar.offsetWidth;

        bar.classList.add('active');
    },

    /**
     * Hide the progress bar
     */
    _hideProgress() {
        let bar = document.getElementById('pjax-progress');
        if (!bar) return;

        bar.classList.remove('active');
        bar.classList.add('done');

        setTimeout(() => {
            bar.classList.remove('done');
            bar.style.width = '0';
        }, 500);
    },
};

window.AdminRouter = AdminRouter;

export default AdminRouter;
