@extends('admin.layout')
@section('title', 'Content Studio Review — Admin')
@section('content')
@fragment('content')
<div data-page-title="Content Studio Review"><div class="d-flex justify-content-between align-items-center mb-3"><div><a data-pjax href="{{ route('admin.content-studio.index') }}">← ინბოქსი</a><h4 class="mt-2">{{ $item->campaign->name }} · {{ $item->channel }}</h4></div><span class="badge bg-secondary">{{ $item->status }}</span></div>
@if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif
<div class="row"><div class="col-lg-8"><div class="card mb-3"><div class="card-header">მიმდინარე რევიზიის Preview</div><div class="card-body">@php($revision = $item->revisions->firstWhere('id', $item->current_revision_id)) @if($revision)<pre class="small bg-light p-3 text-wrap" style="white-space:pre-wrap">{{ json_encode($revision->payload, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES) }}</pre><h6>SEO / AI-readiness</h6>@foreach($revision->validation ?? [] as $check => $pass)<span class="badge me-1 {{ $pass ? 'bg-success' : 'bg-danger' }}">{{ $check }}</span>@endforeach @else <p class="text-muted">რევიზია ჯერ არ არის.</p>@endif</div></div>
<div class="card mb-3"><div class="card-header d-flex justify-content-between"><span>ანალიტიკა</span><span>@foreach([7,28,90] as $days)<a class="btn btn-sm {{ $window === $days ? 'btn-primary' : 'btn-outline-secondary' }}" data-pjax href="{{ route('admin.content-studio.show', ['contentItem' => $item, 'window' => $days]) }}">{{ $days }} დღე</a>@endforeach</span></div><div class="card-body"><p class="small text-muted">GA4/GSC/Meta მონაცემები არის daily read-only snapshots; stale მაჩვენებელი ნიშნავს ბოლო წარმატებულ მნიშვნელობას.</p><div class="row">@forelse($analytics as $source => $snapshot)<div class="col-md-6 mb-2"><div class="border rounded p-2"><b>{{ strtoupper($source) }}</b> <span class="badge bg-{{ $snapshot->status === 'fresh' ? 'success' : ($snapshot->status === 'stale' ? 'warning' : 'danger') }}">{{ $snapshot->status }}</span><pre class="small mb-0">{{ json_encode($snapshot->metrics, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE) }}</pre>@if($snapshot->error)<small class="text-muted">{{ $snapshot->error }}</small>@endif</div></div>@empty<div class="text-muted">ჯერ არ არის snapshot. ყოველდღიური collector ხელმისაწვდომი კონფიგურაციის შემდეგ შეავსებს მონაცემებს.</div>@endforelse</div></div></div>
<div class="card"><div class="card-header">რევიზიები და audit trail</div><div class="list-group list-group-flush">@foreach($item->revisions as $revision)<div class="list-group-item"><b>რევიზია #{{ $revision->revision_number }}</b> · {{ $revision->submitted_at?->timezone(config('app.timezone'))->format('d.m.Y H:i') }} @if($item->approved_revision_id === $revision->id)<span class="badge bg-success">დაბლოკილი / დამტკიცებული</span>@endif @if(!empty($revisionDiffs[$revision->id]))<details class="mt-2"><summary class="small">ცვლილებების diff (წინა რევიზიასთან)</summary><pre class="small mt-2 mb-0">{{ json_encode($revisionDiffs[$revision->id], JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES) }}</pre></details>@endif</div>@endforeach @foreach($item->audits as $event)<div class="list-group-item small text-muted">{{ $event->occurred_at?->timezone(config('app.timezone'))->format('d.m H:i') }} · {{ $event->event }}: {{ $event->from_status }} → {{ $event->to_status }}</div>@endforeach</div></div></div>
<div class="col-lg-4"><div class="card"><div class="card-header">მფლობელის მოქმედება</div><div class="card-body">@if($item->status === 'ready_for_owner')<form class="mb-2" method="POST" action="{{ route('admin.content-studio.approve-now', $item) }}">@csrf<button class="btn btn-success w-100">დამტკიცება და ახლავე გამოქვეყნება</button></form><form class="mb-2" method="POST" action="{{ route('admin.content-studio.schedule', $item) }}">@csrf<label class="form-label small">დაგეგმვა (Asia/Tbilisi)</label><input required type="datetime-local" class="form-control mb-2" name="scheduled_at"><button class="btn btn-primary w-100">დამტკიცება და დაგეგმვა</button></form><hr>@elseif($item->status === 'failed' && $item->approved_revision_id)<form class="mb-2" method="POST" action="{{ route('admin.content-studio.retry', $item) }}">@csrf<button class="btn btn-outline-primary w-100">ხელახლა გამოქვეყნება (დუბლირების გარეშე)</button></form>@endif<form class="mb-2" method="POST" action="{{ route('admin.content-studio.request-changes', $item) }}">@csrf<textarea required name="reviewer_notes" class="form-control mb-2" placeholder="ცვლილებების შენიშვნა"></textarea><button class="btn btn-outline-warning w-100">ცვლილებების მოთხოვნა</button></form><form method="POST" action="{{ route('admin.content-studio.reject', $item) }}">@csrf<textarea required name="reviewer_notes" class="form-control mb-2" placeholder="უარყოფის მიზეზი"></textarea><button class="btn btn-outline-danger w-100">უარყოფა</button></form></div></div><div class="card mt-3"><div class="card-header">მედია / მტკიცებულება</div><div class="card-body small">ვერიფიკაცია: {{ $item->verification_checked_at?->timezone(config('app.timezone'))->format('d.m.Y H:i') ?? '—' }}<hr>@forelse($item->assets as $asset)<div>{{ $asset->mime_type }} · {{ number_format($asset->size_bytes / 1024, 1) }} KB<br><span class="text-muted">{{ $asset->validation['social_compatible'] ?? false ? 'ფორმატი შემოწმებულია' : 'სოციალური URL ჯერ საჭიროებს შემოწმებას' }}</span></div>@empty<span class="text-muted">მედია არ არის ატვირთული</span>@endforelse</div></div></div></div></div>
@endfragment
@endsection
